### ISSUE TITLE
Feature request crosstab by multiple time units

### ISSUE THREAD

**Issue by adam-gruer** [cosimameyer/overviewR#2]
Congrats on a great package.  A feature request if the ime argument could take a list of time unit or ... like in dplyr::select for example.
So something like 
``` r
overview_plot(dat = toydata, id = ccode, time = year, month)
```

**Comment by cosimameyer** [comment]
Thanks so much for the great suggestion! We also had something similar in mind and we'll let you know once it's implemented 😊
