### ISSUE TITLE
recommendation: rename _print to _latex

### ISSUE THREAD

**Issue by drmowinckels** [cosimameyer/overviewR#24]
I'd recommend renaming the `_print` functions to `_latex`. This will make it more clear that the functions create latex output.
Also, it creates a clear distinction from R print methods, that other developers and more advanced users might be familiar with, which is quite different.

as part of https://github.com/openjournals/joss-reviews/issues/4740

**Comment by cosimameyer** [comment]
Thanks so much for this suggestion - that's excellent! I didn't think about it this way (we first envisioned the `overview_print` function to become a much broader function but it remained an `overview_latex` function as it is now and you are right - this name serves its purpose much better 😊). We discussed it internally and are very happy to go forward with your suggestion in PR #26
